# Generated by Django 5.1.4 on 2025-01-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="表名"
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="操作类型"
                    ),
                ),
                (
                    "operation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
            ],
            options={
                "db_table": "operation_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SkiManager",
            fields=[
                (
                    "ManagerID",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="管理者ID",
                    ),
                ),
                ("Passport", models.CharField(max_length=20, verbose_name="管理者登录密码")),
            ],
            options={
                "db_table": "ski_manager",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SkiPurchase",
            fields=[
                (
                    "PurchaseID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("PurchaseTime", models.DateTimeField(auto_now=True)),
                ("PurchaseCost", models.CharField(max_length=20)),
                ("BankcardID", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "ski_purchase",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SkiRental",
            fields=[
                (
                    "RentalID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("EquipmentID", models.CharField(max_length=10)),
                ("RentalStartTime", models.DateTimeField(blank=True, null=True)),
                ("RentalEndTime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ski_rental",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SkiTicket",
            fields=[
                (
                    "TicketsID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("TicketsPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("TicketsStartTime", models.DateTimeField(auto_now=True)),
                ("TicketsEndTime", models.DateTimeField()),
            ],
            options={
                "db_table": "ski_tickets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SkiTrail",
            fields=[
                (
                    "SkiName",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="滑雪道名称",
                    ),
                ),
                ("Difficulty", models.CharField(max_length=20, verbose_name="难度等级")),
                ("SkiDegree", models.FloatField(verbose_name="坡度")),
                ("SkiLength", models.FloatField(verbose_name="长度")),
                ("SkiStatus", models.CharField(max_length=255, verbose_name="滑雪道状态")),
            ],
            options={
                "db_table": "ski_trail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SkiUser",
            fields=[
                (
                    "UsersID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("UsersName", models.CharField(max_length=15)),
                ("UsersPhoneNumber", models.CharField(max_length=20)),
                ("MembershipType", models.CharField(max_length=20)),
                ("RegistrationTime", models.DateTimeField(auto_now=True)),
                ("UsersPassport", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "ski_users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SkiEquipment",
            fields=[
                (
                    "EquipmentID",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="设备ID",
                    ),
                ),
                ("EquipmentName", models.CharField(max_length=20, verbose_name="设备名称")),
                (
                    "EquipmentStatus",
                    models.CharField(max_length=20, verbose_name="设备状态"),
                ),
                (
                    "EquipmentStartime",
                    models.DateTimeField(blank=True, null=True, verbose_name="设备开始时间"),
                ),
                (
                    "EquipmentEndtime",
                    models.DateTimeField(blank=True, null=True, verbose_name="设备结束时间"),
                ),
            ],
            options={
                "db_table": "ski_equipment",
            },
        ),
    ]
