# Generated by Django 5.1.4 on 2025-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SkiApps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSkiInfo",
            fields=[
                (
                    "UsersID",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户ID",
                    ),
                ),
                ("UsersName", models.CharField(max_length=15, verbose_name="用户名称")),
                (
                    "TicketsID",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="雪票ID"
                    ),
                ),
                (
                    "PurchaseID",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="购买记录ID"
                    ),
                ),
                (
                    "EquipmentID",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="设备ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户滑雪信息视图",
                "verbose_name_plural": "用户滑雪信息视图",
                "db_table": "user_ski_info",
                "managed": False,
            },
        ),
    ]
